[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"


[features]
resolution = true
skip-lint = false

[programs.localnet]
newdapp = "6DupSgN4DqaSupZ7db2Cn5s7tMRvR5AaAzT7m2JN7Uf4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

