[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
newdapp = "HbgZigj7TcGwVHs3Z8A5soSmaWEsAAdNsVXaGi5SiDV1"  # Localnet program ID (must match keypair used in deploy)

[programs.devnet]
newdapp = "HbgZigj7TcGwVHs3Z8A5soSmaWEsAAdNsVXaGi5SiDV1"  # Replace with your devnet program ID after deployment

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Changed from localnet to devnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
